<?php
require __DIR__ . '/vendor/autoload.php';
use Facebook\Facebook;
use Facebook\FacebookRequest;

define("APP_ID", "487649851752118");
define("APP_SECRET", "7a9f222a721bc3f716f04c15e0313c59");
define("GRAPH_VERSION", "v3.1");
define("ACCESS_TOKEN", "");

/*
* implements hook_cron()
*/
function facebook_posts_cron() {
  $facebook = new \Facebook\Facebook([
    'app_id' => APP_ID,
    'app_secret' => APP_SECRET,
    'default_graph_version' => GRAPH_VERSION,
    'default_access_token' => ACCESS_TOKEN
  ]);

  try {
    $response = $facebook->get('avwidukind/feed');

  }
  catch(\Facebook\Exceptions\FacebookResponseException $e) {
    drupal_set_message('Graph returned an error: ' . $e->getMessage());
    return;
  } catch(\Facebook\Exceptions\FacebookSDKException $e) {
    // When validation fails or other local issues
    drupal_set_message('Facebook SDK returned an error: ' . $e->getMessage());
    return;
  }
  $feedItems = $response->getGraphEdge();
  foreach($feedItems as $current){
      drupal_set_message(print_r($current, true));
  }
}
